// <auto-generated />
using System;
using JoygameInventory.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JoygameInventory.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20250116102143_netmig02")]
    partial class netmig02
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("JoygameInventory.Data.Entities.InventoryAssigment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignmentDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("InventoryAssigments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignmentDate = new DateTime(2025, 1, 16, 10, 21, 42, 924, DateTimeKind.Utc).AddTicks(2723),
                            ProductId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AssignmentDate = new DateTime(2025, 1, 16, 10, 21, 42, 924, DateTimeKind.Utc).AddTicks(2726),
                            ProductId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            AssignmentDate = new DateTime(2025, 1, 16, 10, 21, 42, 924, DateTimeKind.Utc).AddTicks(2728),
                            ProductId = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            AssignmentDate = new DateTime(2025, 1, 16, 10, 21, 42, 924, DateTimeKind.Utc).AddTicks(2729),
                            ProductId = 6,
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            AssignmentDate = new DateTime(2025, 1, 16, 10, 21, 42, 924, DateTimeKind.Utc).AddTicks(2730),
                            ProductId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            AssignmentDate = new DateTime(2025, 1, 16, 10, 21, 42, 924, DateTimeKind.Utc).AddTicks(2732),
                            ProductId = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 7,
                            AssignmentDate = new DateTime(2025, 1, 16, 10, 21, 42, 924, DateTimeKind.Utc).AddTicks(2733),
                            ProductId = 7,
                            UserId = 5
                        },
                        new
                        {
                            Id = 8,
                            AssignmentDate = new DateTime(2025, 1, 16, 10, 21, 42, 924, DateTimeKind.Utc).AddTicks(2734),
                            ProductId = 8,
                            UserId = 6
                        },
                        new
                        {
                            Id = 9,
                            AssignmentDate = new DateTime(2025, 1, 16, 10, 21, 42, 924, DateTimeKind.Utc).AddTicks(2736),
                            ProductId = 9,
                            UserId = 6
                        });
                });

            modelBuilder.Entity("JoygameInventory.Data.Entities.JoyRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Madbyte"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Joygame"
                        });
                });

            modelBuilder.Entity("JoygameInventory.Data.Entities.JoyStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Document")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("JoyStaffs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "eren.sezen@joygame.com",
                            Name = "Eren",
                            PhoneNumber = "555-0101",
                            Surname = "Sezen",
                            UserName = "eren_sezen"
                        },
                        new
                        {
                            Id = 2,
                            Email = "osman.benlice@joygame.com",
                            Name = "Osman",
                            PhoneNumber = "555-0102",
                            Surname = "Benlice",
                            UserName = "osman_benlice"
                        },
                        new
                        {
                            Id = 3,
                            Email = "onur.unlu@joygame.com",
                            Name = "Onur",
                            PhoneNumber = "555-0103",
                            Surname = "Ünlü",
                            UserName = "onur_unlu"
                        },
                        new
                        {
                            Id = 4,
                            Email = "ali.karatas@joygame.com",
                            Name = "Ali",
                            PhoneNumber = "555-0104",
                            Surname = "Karataş",
                            UserName = "ali_karatas"
                        },
                        new
                        {
                            Id = 5,
                            Email = "ayse.duran@joygame.com",
                            Name = "Ayşe",
                            PhoneNumber = "555-0105",
                            Surname = "Duran",
                            UserName = "ayse_duran"
                        },
                        new
                        {
                            Id = 6,
                            Email = "fatma.ozdemir@joygame.com",
                            Name = "Fatma",
                            PhoneNumber = "555-0106",
                            Surname = "Özdemir",
                            UserName = "fatma_ozdemir"
                        },
                        new
                        {
                            Id = 7,
                            Email = "mehmet.bayar@joygame.com",
                            Name = "Mehmet",
                            PhoneNumber = "555-0107",
                            Surname = "Bayar",
                            UserName = "mehmet_bayar"
                        },
                        new
                        {
                            Id = 8,
                            Email = "hasan.sahin@joygame.com",
                            Name = "Hasan",
                            PhoneNumber = "555-0108",
                            Surname = "Şahin",
                            UserName = "hasan_sahin"
                        },
                        new
                        {
                            Id = 9,
                            Email = "zeynep.kucuk@joygame.com",
                            Name = "Zeynep",
                            PhoneNumber = "555-0109",
                            Surname = "Küçük",
                            UserName = "zeynep_kucuk"
                        },
                        new
                        {
                            Id = 10,
                            Email = "yusuf.bozkurt@joygame.com",
                            Name = "Yusuf",
                            PhoneNumber = "555-0110",
                            Surname = "Bozkurt",
                            UserName = "yusuf_bozkurt"
                        });
                });

            modelBuilder.Entity("JoygameInventory.Data.Entities.JoyUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5adf5870-7ba3-43a0-9d76-10165c2e207f",
                            Email = "eren.sezen@joygame.com",
                            EmailConfirmed = false,
                            FirstName = "Eren",
                            LastName = "Sezen",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "925b425b-5056-457c-8642-c8ca0d9909ae",
                            TwoFactorEnabled = false,
                            UserName = "eren_sezen"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a33e9009-b214-4790-b8c9-480476437fc3",
                            Email = "osman.benlice@joygame.com",
                            EmailConfirmed = false,
                            FirstName = "Jane",
                            LastName = "Doe",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4a751d00-09e5-409a-9a6b-76adab8045f2",
                            TwoFactorEnabled = false,
                            UserName = "osman_benlice"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7abc19b1-6894-41a8-b9a2-19bf5d601ef1",
                            Email = "onur.unlu@joygame.com",
                            EmailConfirmed = false,
                            FirstName = "Onur",
                            LastName = "Ünlü",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "afb003b6-a939-496d-90ee-f0200c2073ec",
                            TwoFactorEnabled = false,
                            UserName = "onur.unlu"
                        });
                });

            modelBuilder.Entity("JoygameInventory.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProductAddDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductBarkod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Depoda");

                    b.Property<string>("img")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "High-performance laptop",
                            ProductAddDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductBarkod = "JGNB054",
                            ProductName = "Laptop",
                            SerialNumber = "3872-5930-4832",
                            Status = "Zimmetli",
                            img = "laptop.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Wireless mouse",
                            ProductAddDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductBarkod = "JGNB060",
                            ProductName = "Mouse",
                            SerialNumber = "3840294-9F5A3C2D",
                            Status = "Zimmetli",
                            img = "mouse.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Mechanical keyboard",
                            ProductAddDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductBarkod = "JGNB024",
                            ProductName = "Keyboard",
                            SerialNumber = "A2B3-5829-20250111",
                            Status = "Zimmetli",
                            img = "keyboard.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Description = "27-inch 4K monitor",
                            ProductAddDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductBarkod = "JGNB095",
                            ProductName = "Monitor",
                            SerialNumber = "WLG-384029-2024",
                            Status = "Zimmetli",
                            img = "monitor.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Noise-cancelling over-ear headphones",
                            ProductAddDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductBarkod = "JGNB101",
                            ProductName = "Headphones",
                            SerialNumber = "HDP-230904",
                            Status = "Zimmetli",
                            img = "headphones.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Description = "128GB USB 3.0 Flash Drive",
                            ProductAddDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductBarkod = "JGNB112",
                            ProductName = "USB Drive",
                            SerialNumber = "USB-3847502",
                            Status = "Zimmetli",
                            img = "usbdrive.jpg"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Latest model smartphone with 5G",
                            ProductAddDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductBarkod = "JGNB130",
                            ProductName = "Smartphone",
                            SerialNumber = "SMP-1234A678",
                            Status = "Zimmetli",
                            img = "smartphone.jpg"
                        },
                        new
                        {
                            Id = 8,
                            Description = "10-inch tablet with stylus support",
                            ProductAddDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductBarkod = "JGNB145",
                            ProductName = "Tablet",
                            SerialNumber = "TAB-5467D2025",
                            Status = "Zimmetli",
                            img = "tablet.jpg"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Fitness smartwatch with heart-rate monitor",
                            ProductAddDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductBarkod = "JGNB162",
                            ProductName = "Smartwatch",
                            SerialNumber = "SW-9476253",
                            img = "smartwatch.jpg"
                        },
                        new
                        {
                            Id = 10,
                            Description = "High-DPI gaming mouse",
                            ProductAddDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductBarkod = "JGNB170",
                            ProductName = "Gaming Mouse",
                            SerialNumber = "GM-845320",
                            img = "gamingmouse.jpg"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Protective laptop sleeve",
                            ProductAddDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductBarkod = "JGNB183",
                            ProductName = "Laptop Sleeve",
                            SerialNumber = "LS-210987",
                            img = "laptopsleeve.jpg"
                        },
                        new
                        {
                            Id = 12,
                            Description = "DSLR camera with 24MP sensor",
                            ProductAddDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductBarkod = "JGNB195",
                            ProductName = "Camera",
                            SerialNumber = "CAM-584230",
                            img = "camera.jpg"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Portable Bluetooth speaker with rich sound",
                            ProductAddDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductBarkod = "JGNB210",
                            ProductName = "Bluetooth Speaker",
                            SerialNumber = "BTS-789403",
                            img = "bluetoothspeaker.jpg"
                        },
                        new
                        {
                            Id = 14,
                            Description = "10,000mAh power bank",
                            ProductAddDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductBarkod = "JGNB230",
                            ProductName = "Power Bank",
                            SerialNumber = "PB-543210",
                            img = "powerbank.jpg"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Virtual reality headset for immersive experiences",
                            ProductAddDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductBarkod = "JGNB245",
                            ProductName = "VR Headset",
                            SerialNumber = "VR-902384",
                            img = "vrheadset.jpg"
                        },
                        new
                        {
                            Id = 16,
                            Description = "2TB external hard drive",
                            ProductAddDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductBarkod = "JGNB260",
                            ProductName = "External Hard Drive",
                            SerialNumber = "EHDD-098723",
                            img = "externalharddrive.jpg"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Ergonomic gaming chair",
                            ProductAddDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductBarkod = "JGNB275",
                            ProductName = "Gaming Chair",
                            SerialNumber = "GC-765493",
                            img = "gamingchair.jpg"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Foldable electric scooter",
                            ProductAddDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductBarkod = "JGNB280",
                            ProductName = "Electric Scooter",
                            SerialNumber = "ES-129845",
                            img = "electricscooter.jpg"
                        },
                        new
                        {
                            Id = 19,
                            Description = "4K camera drone with flight stabilization",
                            ProductAddDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductBarkod = "JGNB295",
                            ProductName = "Drone",
                            SerialNumber = "DRN-589301",
                            img = "drone.jpg"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Portable mini projector",
                            ProductAddDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductBarkod = "JGNB310",
                            ProductName = "Projector",
                            SerialNumber = "PRJ-765123",
                            img = "projector.jpg"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "2",
                            RoleId = "2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("JoygameInventory.Data.Entities.InventoryAssigment", b =>
                {
                    b.HasOne("JoygameInventory.Data.Entities.Product", "Product")
                        .WithMany("InventoryAssigments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JoygameInventory.Data.Entities.JoyStaff", "User")
                        .WithMany("InventoryAssigments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("JoygameInventory.Data.Entities.JoyRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("JoygameInventory.Data.Entities.JoyUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("JoygameInventory.Data.Entities.JoyUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("JoygameInventory.Data.Entities.JoyRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JoygameInventory.Data.Entities.JoyUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("JoygameInventory.Data.Entities.JoyUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JoygameInventory.Data.Entities.JoyStaff", b =>
                {
                    b.Navigation("InventoryAssigments");
                });

            modelBuilder.Entity("JoygameInventory.Data.Entities.Product", b =>
                {
                    b.Navigation("InventoryAssigments");
                });
#pragma warning restore 612, 618
        }
    }
}
